# Generated by Django 4.2.6 on 2023-11-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_user_id_alter_usercontact_user_info'),
        ('service', '0003_servicedetail_service_detail_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_request', models.CharField(max_length=255)),
                ('quote_on_behalf_of', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_date', models.DateTimeField(blank=True, null=True)),
                ('quote_active', models.BooleanField(blank=True, null=True)),
                ('quote_assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_quote_assigned_user', to='user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_requestor', to='user.user')),
            ],
            options={
                'db_table': 'quote',
            },
        ),
        migrations.CreateModel(
            name='QuoteAnswer',
            fields=[
                ('quote_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_answer_description', models.CharField(max_length=255)),
                ('quote_answer_date', models.DateTimeField(blank=True, null=True)),
                ('quote_answer_active', models.BooleanField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_quote', to='quote.quote')),
                ('service_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_service_details', to='service.servicedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_user', to='user.user')),
            ],
            options={
                'db_table': 'quote_answer',
            },
        ),
    ]
