POST http://127.0.0.1:8000/login
Content-Type: : application/json

{"username": "basdi", "password": "iwergj"}

###

POST http://127.0.0.1:8000/signup
Content-Type: : application/json

{"username": "jweiof", "password": "iwergj", "email": "bskfyu@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: : application/json

{}

