# Generated by Django 4.2.6 on 2024-03-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('service_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('service_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_detail_date', models.DateTimeField(blank=True, null=True)),
                ('service_detail_description', models.CharField(blank=True, max_length=255, null=True)),
                ('service_detail_subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('service_detail_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('service_detail_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('service_detail_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('service_detail_active', models.BooleanField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_service', to='service.service')),
            ],
            options={
                'db_table': 'service_detail',
            },
        ),
    ]
