# Generated by Django 4.2.6 on 2023-11-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
