# Generated by Django 4.2.6 on 2023-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_detail_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
