# Generated by Django 4.2.6 on 2024-03-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_info_name', models.CharField(max_length=255)),
                ('user_info_id_card', models.CharField(max_length=12, unique=True)),
                ('user_info_tel_number', models.CharField(max_length=12, unique=True)),
                ('user_info_email', models.EmailField(max_length=30, unique=True)),
                ('user_info_address', models.CharField(max_length=255)),
                ('user_info_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role_name', models.CharField(max_length=20, unique=True)),
                ('user_role_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('user_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_contact_number', models.CharField(max_length=12, unique=True)),
                ('user_contact_name', models.CharField(max_length=255)),
                ('user_contact_active', models.BooleanField(blank=True, null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_c', to='user.userinfo')),
            ],
            options={
                'db_table': 'user_contact',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='_user', serialize=False, to='user.userinfo')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_active', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userrole')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
