# Generated by Django 4.2.6 on 2023-11-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_info_name', models.CharField(max_length=255)),
                ('user_info_id_card', models.CharField(max_length=12, unique=True)),
                ('user_info_tel_number', models.CharField(max_length=12, unique=True)),
                ('user_info_email', models.CharField(max_length=30, unique=True)),
                ('user_info_address', models.CharField(max_length=255)),
                ('user_info_active', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role_name', models.CharField(max_length=20, unique=True)),
                ('user_role_active', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('user_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_contact_number', models.CharField(max_length=12, unique=True)),
                ('user_contact_name', models.CharField(max_length=255)),
                ('user_contact_active', models.TextField(blank=True, null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userinfo')),
            ],
            options={
                'db_table': 'user_contact',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.userinfo')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_email', models.CharField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_active', models.TextField(blank=True, null=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userrole')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
