# Generated by Django 4.2.6 on 2023-11-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='_user', serialize=False, to='user.userinfo'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_c', to='user.userinfo'),
        ),
    ]
