# Generated by Django 4.2.6 on 2024-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
