# Generated by Django 4.2.6 on 2024-05-08 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method_info', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('sales_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_status_name', models.CharField(max_length=20, unique=True)),
                ('sales_status_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_status',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateTimeField()),
                ('sales_subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sales_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.paymentmethod')),
                ('sales_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.salesstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
