# Generated by Django 4.2.6 on 2024-05-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesdetail_product_salesdetail_sales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdetail',
            options={},
        ),
    ]
