# Generated by Django 4.2.6 on 2024-03-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(max_length=23, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchasediscount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_active', models.BooleanField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchase_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_detail_prod_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_detail_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_detail_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('purchase_detail_quantity', models.IntegerField()),
                ('purchase_detail_subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_product', to='product.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.purchase')),
            ],
            options={
                'db_table': 'purchase_detail',
            },
        ),
    ]
