# Generated by Django 4.2.6 on 2023-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productspecsheet',
            name='product_spec_sheet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
