# Generated by Django 4.2.6 on 2024-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id_card', models.CharField(max_length=12, unique=True)),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_active', models.BooleanField(blank=True, null=True)),
                ('supplier_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
